version: '3.8'
services:
  api:
    build:
      context: .
    container_name: personia
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      JAVA_ENV: dev
      DATABASE_URL: jdbc:postgresql://db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres1234
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: postgres
  db:
    image: postgres:14.1-alpine
    container_name: personia-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local